### PR TITLE
[FIX][IMPROVE] Add cleanup script and fix the docker error loop

### PR DESCRIPTION
**Pull request by Dnouv**
Changes in the PR:
Added script logic to do the following
- [x] On Ctrl+C, stop and remove the containers.
- [x] Auto re-run the scripts (OES and Fauna Images) 5 times before exiting.

Thank you!

Fixes: #39

### CODE REVIEW

**Comment by Sing-Li** [comment]
@Dnouv   the script still expects the correct version of nodeJS and npm has ALREADY been installed in the base system.   If that is not the case, the script crashes and burns 😞     

Adding volta install into the script MAY solve the problem.  But please anticipate systems where THE WRONG VERSION of nodeJS is already installed and code accordingly.  Thanks.

**Comment by Dnouv** [comment]
Thank you for the review; I will add the volta script.

**Comment by Dnouv** [comment]
@Sing-Li, now the script works for the VM or any other IP addresses. 

I think adding volta ain't good for our project since any new contributor won't prefer to install a global dependency (`volta`) just to try out a single Open Source project. So I did all the checks using UNIX scripts; I hope that would be ok.

Thoughts?
(Please merge it before testing PR#35, once this is merged, I will rebase these changes on PR#35. And then it should work for you.)
Thank you!

**Comment by Sing-Li** [comment]
> now the script works for the VM or any other IP addresses

Thanks.   This is very important as we cannot assume the configuration of tester/contributor;  plus hardcoding localhost magic constant is just not a good coding practice 

> I think adding volta ain't good for our project since any new contributor won't prefer to install a global 
>  dependency (volta) just to try out a single Open Source project. So I did all the checks using UNIX scripts; 
> I hope that would be ok.

I am merging this PR so you can move on with the fix.     Will answer this offline.

**Pull request merged**
