### PR TITLE
[CLONE] Clone open event server

### PR DESCRIPTION
**Pull request by Dnouv**
This PR clones the open-event-server into `open-event-server`.

Thank you!

### CODE REVIEW

**Review by Sing-Li — CHANGES_REQUESTED** [review]
Do we need all of the dot files in this directory?

**Comment by Dnouv** [comment]
yes, we might need them in the future. I have removed some files which didn't seem that important, mainly an editor config file and a git blame file.

Thank you!

**Comment by Sing-Li** [comment]
Please remove everything that you don't know why it is there and not using right now.

For the future, when we need it, we can add it back.

**Comment by Sing-Li** [comment]
Also I don't think we can remove the existing license file. Please add it back.

**Comment by Dnouv** [comment]
Removed almost all the not present required `.files` and retrieved the license.

Thank you!

**Review by Sing-Li — APPROVED** [review]

**Pull request merged**
