### PR TITLE
Add a check for data exist in env file to avoid some redundant data gets accumulated in .env file.

### LINKED ISSUE #66: Redundant data in .env file
On running the command `sh startdevenv.sh localhost` some data gets added in the env file every time we run it, because of which some redundant data gets accumulated in .env file.

### PR DESCRIPTION
**Pull request by VipinDevelops**
Fixes the issue of redundant data being added to the app/.env file every time the startdevenv.sh script is run.

Previously, the script appended certain data to the app/.env file every time it was run, resulting in the accumulation of duplicate data in the file.

To fix this issue, I have added a check in the script that verifies if the variables already exist in the app/.env file before appending them to the file. This ensures that only new or updated variables will be added to the file, preventing the accumulation of redundant data.

Fixes #66

### CODE REVIEW

**Comment by debdutdeb** [comment]
Why not delete the file at the beginning, if it already exists?

**Comment by VipinDevelops** [comment]
You mean completely clear the .env before starting script

**Comment by debdutdeb** [comment]
Yes

**Comment by VipinDevelops** [comment]
yeah sure we can do that as well 
so should I implement that ?

**Comment by Dnouv** [comment]
> yeah sure we can do that as well so should I implement that ?

No, you don't. Please carefully go through my comments on the issue, this approach will not work and crash the local setup, I have explained it more in detail on the issue. 

Thank you!

**Comment by VipinDevelops** [comment]
Sorry @Dnouv  i just finished reading your comments will surley make changes to this PR like you asked can you explain a bit which approach i should use to fix this issue

that would help alot to help me get this issue fixed

**Comment by Palanikannan1437** [comment]
> Sorry @Dnouv i just finished reading your comments will surley make changes to this PR like you asked can you explain a bit which approach i should take to fix this issue
> 
> that would help alot to help me get this issue fixed

As @Dnouv suggested, please try to explore how the scripts work in RC4Conferences and essentially google is your best friend, on top of my mind...the `sed` command might help you to replace variables dynamically with some custom thought out logic 🚀

**Comment by Dnouv** [comment]
Hey @VipinDevelops 

Are you still working on this PR? If you are, please let us know. Or we can close this PR. Thank you!

**Comment by VipinDevelops** [comment]
Sorry i forgot to drop a message i am working on this will soon make a PR 

😅kind a busy with college exams

**Comment by VipinDevelops** [comment]
i'll make a new PR fixing this same issue Can you please check the new approach I shared here is a link to it https://github.com/RocketChat/RC4Conferences/issues/66#issuecomment-1403410289

**Pull request closed without merging**
