### PR TITLE
[FIX]: Event Alert close button #77

### PR DESCRIPTION
**Pull request by Aashray446**
* Add toggle state function to close custom toast
 * Add a close prop to the custom toast
pr-7

### CODE REVIEW

**Comment by Aashray446** [comment]
@Dnouv  I have created this pull request for issue #77, as most TODO are around those pages and components, it's a little bit annoying while testing and creating an Event.
Also, this issue was there for so long and inactive so I raised the PR without being assigned, I apologize for this. 

Thank you!

**Comment by SarveshLimaye** [comment]
@Aashray446 Thank you for the pr. We need to create a new component that displays alerts in the top right corner similar to one in Rocket chat. I was too busy working on other pr and did not update the title of the issue. Currently, I am working on this issue. You can look up to other open issues and work on them.

**Comment by Aashray446** [comment]
Oh ok that's great. Sorry , I thought there is no activity in this issue so I solved

Thanks 🙏

**Comment by Dnouv** [comment]
Thank you, @SarveshLimaye, for making things clear. And thanks for the hard work on the PR @Aashray446; we really appreciate your time and dedication; this is the case that I was worried about if someone opened up a PR without explaining the issue. I would add it to the contribution guideline so that others' time won't be wasted. 

I apologize for the inconvenience, and thank you once again, @Aashray446 . Since you have been so active in RC4Conferences, it would be good if you can open up any new feature requests that you think would be a good addition.

**Comment by Aashray446** [comment]
Thanks, @Dnouv for the recognization and for believing in me. Currently, I am looking forward to implementing the new text area component as it will be used in many places in the future, and contributing a component to the project make me feel a little proud :sweat_smile:

I have mentioned the library choices for making that component in issue #105,  Waiting for your valuable suggestion 
Thanks :smile:

**Pull request closed without merging**
