### PR TITLE
[NEW] Improve Navbar #73

### PR DESCRIPTION
**Pull request by Aashray446**
### Working Screenshot
pr-2

### CODE REVIEW

**Comment by Dnouv** [comment]
Hey @Aashray446 

Thanks for the PR. Could you please fix the style of the "Click to Chat" button? In the screenshots, there is an unusual spacing between them.
And also, do not display the "Click to Chat" button when the user is not logged in. 
Thank you!

**Comment by Aashray446** [comment]
Ok sure, I will rectify those things soon 🙂

**Comment by Aashray446** [comment]
Currently the spacing is adjusted evenly between the navbar child components, Should I shift the 'click to chat ' button near the profile?

**Comment by Aashray446** [comment]
Currently the spacing is adjusted evenly between the navbar child components, Should I shift the 'click to chat ' button near the profile?

**Comment by Aashray446** [comment]
Currently the spacing is adjusted evenly between the navbar child components, Should I shift the 'click to chat ' button near the profile?

**Comment by Dnouv** [comment]
Yes, it should be near the avatar button.

**Comment by r3yc0n1c** [comment]
also the 404 seems odd with the centered navbar... shall we stretch it to full width? (ref https://conf.rceng.shop/xyz)

**Pull request closed without merging**
