### PR TITLE
Migrate current authentication setup to NextAuth

### PR DESCRIPTION
**Pull request by adarsh500**
This PR Completes #42 

- [x] google OAuth
- [x]  GitHub OAuth
- [x]  email + password

### CODE REVIEW

**Comment by Dnouv** [comment]
Hey @adarsh500 
Any updates for this PR? 

Thanks!

**Comment by adarsh500** [comment]
It's almost complete, the only thing left to do is 2FA with Google oauth. There are a couple of ways we could do this
1. use a combination of the current gapi with nextAuth or 
2. Write a custom NextAuth provider (there is a possibility that this might require some backend changes)

I aim to finish it by this weekend, please let me know if you have any thoughts/suggestions. 
Thanks :)

**Comment by Dnouv** [comment]
> Write a custom NextAuth provider (there is a possibility that this might require some backend changes)

We would prefer it to be done this way to maintain the Auth consistency. Thank you!

**Comment by adarsh500** [comment]
Hey @Dnouv, i'm stuck trying to figure out how to pass additional parameters to the next auth API while signing up with google. As of now we can't use a state param because the library does not support it as it would conflict with the state param that the library uses internally. This is the last part of it and I'm stuck here, any help would be appreciated, thanks

**Comment by Dnouv** [comment]
Why would you need to pass extra param? Are you trying to pass the 2fa token?

**Comment by Dnouv** [comment]
@adarsh500 if it's something related to 2fa, in RC you can pass the 2fa token as a header:
```
-H "X-2fa-code: $SHA_256_HASH_OF_API_USER_PASSWORD" \
-H "X-2fa-method: password" 
```

**Comment by Dnouv** [comment]
Hey @adarsh500 

Any progress?

Thanks!

**Comment by adarsh500** [comment]
Hey @Dnouv, 2FA works flawlessly, thanks for helping me out with the last part. It's ready for review

**Comment by Dnouv** [comment]
@adarsh500 could you please resolve the conflicts and the failing tests? Thank you!

**Comment by adarsh500** [comment]
@Dnouv will resolve the conflicts and failed test today

**Review by Dnouv — APPROVED** [review]
LGTM! Thanks for the PR.

PS. There were some minor changes left to correct. But I will do it myself. For e.g., "hashmeth" instead of "hashmail"

**Pull request merged**
